[package]
edition = "2018"
name = "centrifuge-rs"
version = "0.1.0"

[dependencies]
websocket = "0.26"
prost = "0.9.0"
anyhow = "*"
thiserror = "*"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = { version = "0.9.0" }

